from pathlib import Path
from typing import Optional
import os
import sys

import questionary

COMPATIBLE_SHELLS = {
    "zsh": Path.home() / ".zshrc",
    "bash": Path.home() / ".bashrc",
}


def select_shell() -> Optional[str]:
    detected = Path(os.environ.get("SHELL", "")).name

    if detected in COMPATIBLE_SHELLS:
        if questionary.confirm(
            f"Detected '{detected}'. Use this shell?",
            default=True,
        ).ask():
            return detected

    shell = questionary.select(
        "Select your shell:",
        choices=[*COMPATIBLE_SHELLS.keys(), "Cancel"],
    ).ask()

    if shell == "Cancel":
        return None

    return shell


def build_alias_file() -> Path:
    project_root = Path(__file__).parent
    aliases_dir = project_root / "aliases"

    if not aliases_dir.exists():
        print("❌ The 'aliases' directory was not found.")
        sys.exit(1)

    alias_files = sorted(aliases_dir.glob("*.alias"))

    if not alias_files:
        print("❌ No .aliases files were found.")
        sys.exit(1)

    target_file = Path.home() / ".qvdx-aliases"

    with target_file.open("w") as output:
        output.write("# ==============================================\n")
        output.write("# This file is automatically generated.\n")
        output.write("# Do not edit manually.\n")
        output.write("# ==============================================\n\n")

        for alias_file in alias_files:
            output.write(f"# ----- {alias_file.name} -----\n\n")
            output.write(alias_file.read_text())
            output.write("\n\n")

    return target_file


def update_shell_config(shell: str, aliases_file: Path):
    rc_file = COMPATIBLE_SHELLS[shell]

    if not rc_file.exists():
        rc_file.touch()

    source_line = f'[ -f "{aliases_file}" ] && source "{aliases_file}"'

    content = rc_file.read_text()

    if source_line not in content:
        with rc_file.open("a") as f:
            f.write("\n# Added by qvdx\n")
            f.write(source_line)
            f.write("\n")

    return rc_file


def main():
    print("Alias installer (by: qvdx)\n")

    shell = select_shell()

    if shell is None:
        print("Installation cancelled.")
        return

    aliases_file = build_alias_file()
    rc_file = update_shell_config(shell, aliases_file)

    print("\n✅ Installation completed successfully!")
    print(f"Aliases file : {aliases_file}")
    print(f"Shell config : {rc_file}")
    print("\nRun:")
    print(f"source {rc_file}")
    print("\nor restart your terminal.")


if __name__ == "__main__":
    main()
